CREATE OR REPLACE WAREHOUSE SNOWFLAKE_ML_WH;
CREATE OR REPLACE DATABASE SNOWFLAKE_ML_DB;
CREATE OR REPLACE SCHEMA SNOWFLAKE_ML_SCHEMA;
CREATE OR REPLACE STAGE SNOWFLAKE_ML_ASSETS;

CREATE FILE FORMAT IF NOT EXISTS SNOWFLAKE_ML_DB.SNOWFLAKE_ML_SCHEMA.CSVFORMAT 
    SKIP_HEADER = 1 
    TYPE = 'CSV';

CREATE STAGE IF NOT EXISTS SNOWFLAKE_ML_DB.SNOWFLAKE_ML_SCHEMA.DAILY_DELHI_CLIMATE_ASSETS 
    FILE_FORMAT = SNOWFLAKE_ML_DB.SNOWFLAKE_ML_SCHEMA.CSVFORMAT;

PUT 'file://D:/Snowflake/Snowflake ML/Forecasting/Daily Climate time series data/DailyDelhiClimateTrain.csv'
    @DAILY_DELHI_CLIMATE_ASSETS;

PUT 'file://D:/Snowflake/Snowflake ML/Forecasting/Daily Climate time series data/DailyDelhiClimateTest.csv'
    @DAILY_DELHI_CLIMATE_ASSETS;

LS @DAILY_DELHI_CLIMATE_ASSETS;