CREATE OR REPLACE WAREHOUSE SNOWFLAKE_ML_WH;
CREATE OR REPLACE DATABASE SNOWFLAKE_ML_DB;
CREATE OR REPLACE SCHEMA SNOWFLAKE_ML_SCHEMA;
CREATE OR REPLACE STAGE SNOWFLAKE_ML_ASSETS;

CREATE FILE FORMAT IF NOT EXISTS SNOWFLAKE_ML_DB.SNOWFLAKE_ML_SCHEMA.CSVFORMAT 
    SKIP_HEADER = 1 
    TYPE = 'CSV';

CREATE STAGE IF NOT EXISTS SNOWFLAKE_ML_DB.SNOWFLAKE_ML_SCHEMA.HEART_ATTACK_ASSESTS
    FILE_FORMAT = SNOWFLAKE_ML_DB.SNOWFLAKE_ML_SCHEMA.CSVFORMAT;

PUT 'file://D:/Snowflake/Snowflake ML/Classification/Heart_Attack_Analysis_&_Prediction_Dataset.csv'
    @HEART_ATTACK_ASSESTS;

LS @HEART_ATTACK_ASSESTS;